language: android
jdk:
  - oraclejdk8
notifications:
  email: false
  slack: annaforandroid:ULrbK43z266SCMhYr471J9hF
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-25
before_install:
  - chmod +x ./ANNA/gradlew
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
script:
  - ./ANNA/gradlew build -b ./ANNA/build.gradle -PdisablePreDex
after_success:
  - ./upload-apk.sh
