language: android 
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.3
    - android-24
before_install:
  - chmod +x ./ANNA/gradlew
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA8_HOME
script:
  - ./ANNA/gradlew build
after_success:
  - ./upload-apk.sh